import { NextResponse } from "next/server"
import { generateText } from "ai"

export async function POST(request: Request) {
  try {
    const { prompt } = await request.json()

    const { text } = await generateText({
      model: "anthropic/claude-sonnet-4.5",
      prompt: `You are Crowe Code, an autonomous AI developer specializing in agricultural data analysis and mushroom cultivation research.

User Request: ${prompt}

Generate production-ready Python code for this request. The code should:
- Be clean, well-commented, and research-grade
- Use pandas, numpy, matplotlib for data analysis
- Connect to Supabase database when needed
- Include error handling
- Be immediately executable

Generate only the code with minimal explanation.`,
      temperature: 0.3,
      maxTokens: 2000,
    })

    // Extract code from response
    const codeMatch = text.match(/```python\n([\s\S]*?)\n```/)
    const code = codeMatch ? codeMatch[1] : text

    return NextResponse.json({
      code,
      language: "python",
      explanation: "Code generated by Crowe Code autonomous system",
    })
  } catch (error) {
    console.error("[v0] Crowe Code autonomous error:", error)
    return NextResponse.json({ error: "Failed to generate code" }, { status: 500 })
  }
}
