export const runtime = "edge"

interface FileEntry {
  path: string
  code: string
  language?: string
}

interface ExportProjectRequest {
  files: FileEntry[]
  projectName?: string
}

export async function POST(req: Request) {
  try {
    const { files, projectName = "crowe-code-project" }: ExportProjectRequest = await req.json()

    if (!files || files.length === 0) {
      return new Response(JSON.stringify({ error: "No files provided" }), {
        status: 400,
        headers: { "Content-Type": "application/json" },
      })
    }

    // For now, we'll create a simple archive format (can be upgraded to ZIP later)
    // Create a structured text file with all files
    let archiveContent = `# ${projectName}\n# Generated by Crowe Logic Research IDE\n# ${new Date().toISOString()}\n\n`

    files.forEach((file) => {
      archiveContent += `\n${"=".repeat(80)}\n`
      archiveContent += `FILE: ${file.path}\n`
      archiveContent += `${"=".repeat(80)}\n\n`
      archiveContent += file.code
      archiveContent += "\n\n"
    })

    // Add a manifest at the end
    archiveContent += `\n${"=".repeat(80)}\n`
    archiveContent += `PROJECT MANIFEST\n`
    archiveContent += `${"=".repeat(80)}\n\n`
    archiveContent += `Files included:\n`
    files.forEach((file, index) => {
      archiveContent += `${index + 1}. ${file.path}\n`
    })

    return new Response(archiveContent, {
      headers: {
        "Content-Type": "application/octet-stream",
        "Content-Disposition": `attachment; filename="${projectName}.txt"`,
        "Cache-Control": "no-cache",
      },
    })
  } catch (error) {
    console.error("[Export Project API] Error:", error)
    return new Response(
      JSON.stringify({
        error: "Failed to export project",
        details: error instanceof Error ? error.message : String(error),
      }),
      {
        status: 500,
        headers: { "Content-Type": "application/json" },
      },
    )
  }
}
