export const runtime = "edge"

interface FileEntry {
  path: string
  code: string
  language?: string
}

interface ExportProjectRequest {
  files: FileEntry[]
  projectName?: string
}

import JSZip from "jszip"

const MAX_FILES = 500
const MAX_TOTAL_BYTES = 3 * 1024 * 1024 // 3 MB soft cap for edge function

export async function POST(req: Request) {
  try {
    const url = new URL(req.url)
    const format = url.searchParams.get("format") || "zip" // default to zip
    const { files, projectName = "crowe-code-project" }: ExportProjectRequest = await req.json()

    if (!files || files.length === 0) {
      return new Response(JSON.stringify({ error: "No files provided" }), {
        status: 400,
        headers: { "Content-Type": "application/json" },
      })
    }

    // Validate limits
    if (files.length > MAX_FILES) {
      return new Response(JSON.stringify({ error: `Too many files. Max ${MAX_FILES}` }), {
        status: 413,
        headers: { "Content-Type": "application/json" },
      })
    }

    const totalBytes = files.reduce((sum, f) => sum + (f.code?.length || 0), 0)
    if (totalBytes > MAX_TOTAL_BYTES) {
      return new Response(JSON.stringify({ error: `Export too large. Limit ${(MAX_TOTAL_BYTES / (1024*1024)).toFixed(1)}MB` }), {
        status: 413,
        headers: { "Content-Type": "application/json" },
      })
    }

    // ZIP format (default)
    if (format === "zip") {
      const encoder = new TextEncoder()
      async function sha256Hex(bytes: Uint8Array) {
        const hashBuffer = await crypto.subtle.digest("SHA-256", bytes as unknown as BufferSource)
        const hashArray = Array.from(new Uint8Array(hashBuffer))
        return hashArray.map((b) => b.toString(16).padStart(2, "0")).join("")
      }

      const zip = new JSZip()
      const root = zip.folder(projectName) || zip
      const entriesMeta: { path: string; size: number; sha: string }[] = []
      for (const file of files) {
        const normalized = (file.path || "").replace(/^\/+/, "") || "file.txt"
        const bytes = encoder.encode(file.code ?? "")
        const sha = await sha256Hex(bytes)
        entriesMeta.push({ path: normalized, size: bytes.byteLength, sha })
        root.file(normalized, bytes, { createFolders: true })
      }
      const totalSize = entriesMeta.reduce((a, e) => a + e.size, 0)
      const manifest = [
        `project: ${projectName}`,
        `generated: ${new Date().toISOString()}`,
        `files: ${files.length}`,
        `total-bytes: ${totalSize}`,
        "",
        "# file list (size bytes, sha256)",
        ...entriesMeta.map((e, i) => `${i + 1}. ${e.path}\n   size: ${e.size}\n   sha256: ${e.sha}`),
        "",
      ].join("\n")
      root.file("PROJECT_MANIFEST.txt", manifest)
      const content = await zip.generateAsync({ type: "uint8array", compression: "DEFLATE", compressionOptions: { level: 6 } })
      // Wrap in ReadableStream to satisfy streaming requirement (single chunk)
      const stream = new ReadableStream<Uint8Array>({
        start(controller) {
          controller.enqueue(content)
          controller.close()
        }
      })
      return new Response(stream, {
        headers: {
          "Content-Type": "application/zip",
          "Content-Disposition": `attachment; filename="${projectName}.zip"`,
          "Cache-Control": "no-cache",
        },
      })
    }

    // Plain text fallback archive
    let archiveContent = `# ${projectName}\n# Generated by Crowe Logic Research IDE\n# ${new Date().toISOString()}\n\n`

    files.forEach((file) => {
      archiveContent += `\n${"=".repeat(80)}\n`
      archiveContent += `FILE: ${file.path}\n`
      archiveContent += `${"=".repeat(80)}\n\n`
      archiveContent += file.code
      archiveContent += "\n\n"
    })

    // Add a manifest at the end
    archiveContent += `\n${"=".repeat(80)}\n`
    archiveContent += `PROJECT MANIFEST\n`
    archiveContent += `${"=".repeat(80)}\n\n`
    archiveContent += `Files included:\n`
    files.forEach((file, index) => {
      archiveContent += `${index + 1}. ${file.path}\n`
    })

    return new Response(archiveContent, {
      headers: {
        "Content-Type": "text/plain; charset=utf-8",
        "Content-Disposition": `attachment; filename="${projectName}.txt"`,
        "Cache-Control": "no-cache",
      },
    })
  } catch (error) {
    console.error("[Export Project API] Error:", error)
    return new Response(
      JSON.stringify({
        error: "Failed to export project",
        details: error instanceof Error ? error.message : String(error),
      }),
      {
        status: 500,
        headers: { "Content-Type": "application/json" },
      },
    )
  }
}
