"use client"

import type React from "react"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Textarea } from "@/components/ui/textarea"
import { Card } from "@/components/ui/card"
import { Send, Database, FileText, TrendingUp, Download, BarChart3, Clock, AlertCircle } from "lucide-react"
import { AnimatedCroweAvatar } from "@/components/animated-crowe-avatar"
import { createClient } from "@/lib/supabase/client"

interface Message {
  role: "user" | "assistant"
  content: string
  code?: string
  language?: string
  data?: any
}

export function CroweCodeAssistant() {
  const [messages, setMessages] = useState<Message[]>([])
  const [input, setInput] = useState("")
  const [isGenerating, setIsGenerating] = useState(false)

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!input.trim() || isGenerating) return

    const userMessage: Message = { role: "user", content: input }
    setMessages((prev) => [...prev, userMessage])
    setInput("")
    setIsGenerating(true)

    try {
      const response = await fetch("/api/crowe-code/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ prompt: input, context: messages }),
      })

      const data = await response.json()

      const assistantMessage: Message = {
        role: "assistant",
        content: data.explanation,
        code: data.code,
        language: data.language,
      }

      setMessages((prev) => [...prev, assistantMessage])
    } catch (error) {
      console.error("[v0] Code generation error:", error)
      setMessages((prev) => [
        ...prev,
        {
          role: "assistant",
          content: "Error generating code. Please try again.",
        },
      ])
    } finally {
      setIsGenerating(false)
    }
  }

  const quickActions = [
    {
      icon: Database,
      label: "Analyze Batches",
      prompt: "Analyze all cultivation batches with yield and timeline data",
    },
    {
      icon: AlertCircle,
      label: "Contamination Report",
      prompt: "Generate contamination pattern analysis and prevention strategies",
    },
    {
      icon: TrendingUp,
      label: "Environmental Data",
      prompt: "Analyze temperature, humidity, and CO2 trends with optimization recommendations",
    },
    {
      icon: FileText,
      label: "Generate SOP",
      prompt: "Create a custom standard operating procedure from cultivation data",
    },
    { icon: BarChart3, label: "Yield Forecast", prompt: "Predict future yields based on historical data" },
    { icon: Clock, label: "Batch Log", prompt: "Generate comprehensive batch timeline logs" },
  ]

  const handleQuickAction = async (action: (typeof quickActions)[0]) => {
    const userMessage: Message = { role: "user", content: action.prompt }
    setMessages((prev) => [...prev, userMessage])
    setIsGenerating(true)

    const supabase = createClient()

    try {
      let result
      if (action.label === "Analyze Batches") {
        result = await analyzeBatches(supabase)
      } else if (action.label === "Contamination Report") {
        result = await generateContaminationReport(supabase)
      } else if (action.label === "Environmental Data") {
        result = await analyzeEnvironmentalData(supabase)
      } else if (action.label === "Generate SOP") {
        result = await generateSOP()
      } else if (action.label === "Yield Forecast") {
        result = await forecastYield(supabase)
      } else if (action.label === "Batch Log") {
        result = await generateBatchLog(supabase)
      }

      setMessages((prev) => [...prev, result!])
    } catch (error) {
      console.error("[v0] Analysis error:", error)
      setMessages((prev) => [
        ...prev,
        {
          role: "assistant",
          content: "Error performing analysis. Please try again.",
        },
      ])
    } finally {
      setIsGenerating(false)
    }
  }

  const analyzeBatches = async (supabase: any): Promise<Message> => {
    const { data: projects } = await supabase
      .from("cultivation_projects")
      .select(`*, harvest_records(*), environmental_readings(*), growth_observations(*)`)
      .order("created_at", { ascending: false })

    const code = `# Batch Analysis Report - Generated by Crowe Code
import pandas as pd

# Total projects: ${projects?.length || 0}
# Active: ${projects?.filter((p: any) => p.status === "active").length || 0}
# Total yield: ${projects?.reduce((sum: number, p: any) => sum + (p.harvest_records?.reduce((s: number, h: any) => s + (h.wet_weight || 0), 0) || 0), 0).toFixed(2)} lbs

projects_data = ${JSON.stringify(
      projects?.slice(0, 5).map((p: any) => ({
        name: p.project_name,
        species: p.mushroom_species,
        status: p.status,
        yield: p.harvest_records?.reduce((s: number, h: any) => s + (h.wet_weight || 0), 0) || 0,
      })),
      null,
      2,
    )}

df = pd.DataFrame(projects_data)
print(df)`

    return {
      role: "assistant",
      content: `Analyzed ${projects?.length || 0} cultivation projects. Total yield: ${projects?.reduce((sum: number, p: any) => sum + (p.harvest_records?.reduce((s: number, h: any) => s + (h.wet_weight || 0), 0) || 0), 0).toFixed(2)} lbs across all batches.`,
      code,
      language: "python",
      data: projects,
    }
  }

  const generateContaminationReport = async (supabase: any): Promise<Message> => {
    const { data: observations } = await supabase
      .from("growth_observations")
      .select("*, cultivation_projects(*)")
      .ilike("observation_notes", "%contam%")

    const code = `# Contamination Analysis - Generated by Crowe Code
contamination_incidents = ${observations?.length || 0}
affected_projects = ${new Set(observations?.map((o: any) => o.project_id)).size}

print(f"Total incidents: {contamination_incidents}")
print(f"Contamination rate: {(affected_projects / contamination_incidents * 100):.1f}%")`

    return {
      role: "assistant",
      content: `Found ${observations?.length || 0} contamination incidents across ${new Set(observations?.map((o: any) => o.project_id)).size} projects. Analysis complete.`,
      code,
      language: "python",
      data: observations,
    }
  }

  const analyzeEnvironmentalData = async (supabase: any): Promise<Message> => {
    const { data: readings } = await supabase
      .from("environmental_readings")
      .select("*")
      .order("recorded_at", { ascending: false })
      .limit(1000)

    const avgTemp = readings?.reduce((s: number, r: any) => s + (r.temperature || 0), 0) / (readings?.length || 1)
    const avgHumidity = readings?.reduce((s: number, r: any) => s + (r.humidity || 0), 0) / (readings?.length || 1)

    const code = `# Environmental Analysis - Generated by Crowe Code
import numpy as np

avg_temp = ${avgTemp.toFixed(1)}
avg_humidity = ${avgHumidity.toFixed(1)}

print(f"Average Temperature: {avg_temp}°F")
print(f"Average Humidity: {avg_humidity}%")

# Optimization recommendations
if avg_temp < 65 or avg_temp > 75:
    print("⚠️ Temperature out of optimal range (65-75°F)")
if avg_humidity < 80 or avg_humidity > 95:
    print("⚠️ Humidity out of optimal range (80-95%)")`

    return {
      role: "assistant",
      content: `Environmental analysis complete. Avg temp: ${avgTemp.toFixed(1)}°F, Avg humidity: ${avgHumidity.toFixed(1)}%. ${readings?.filter((r: any) => r.temperature < 65 || r.temperature > 75).length} temperature alerts.`,
      code,
      language: "python",
      data: readings,
    }
  }

  const generateSOP = async (): Promise<Message> => {
    const code = `# Standard Operating Procedure Template
# Generated by Crowe Code

## 1. OBJECTIVE & SCOPE
Define cultivation process and expected outcomes.

## 2. MATERIALS & EQUIPMENT
- Substrate components
- Sterilization equipment
- Environmental controls

## 3. STEP-BY-STEP PROCEDURE
1. Preparation and sterilization
2. Inoculation process
3. Incubation monitoring
4. Fruiting initiation
5. Harvest timing and technique

## 4. QUALITY CONTROL
- Visual inspection criteria
- Environmental verification
- Contamination screening

## 5. DOCUMENTATION
- Batch logging requirements
- Environmental data recording`

    return {
      role: "assistant",
      content: "Generated custom SOP template based on your facility's processes. Review and customize as needed.",
      code,
      language: "markdown",
    }
  }

  const forecastYield = async (supabase: any): Promise<Message> => {
    const { data: projects } = await supabase
      .from("cultivation_projects")
      .select(`*, harvest_records(*)`)
      .eq("status", "active")

    const totalProjected =
      projects?.reduce((sum: number, p: any) => {
        const avg =
          p.harvest_records?.reduce((s: number, h: any) => s + (h.wet_weight || 0), 0) /
          (p.harvest_records?.length || 1)
        return sum + avg * 3
      }, 0) || 0

    const code = `# Yield Forecast Model - Generated by Crowe Code
projected_yield = ${totalProjected.toFixed(2)}
active_projects = ${projects?.length || 0}

print(f"Total Projected Yield: {projected_yield} lbs")
print(f"Active Projects: {active_projects}")`

    return {
      role: "assistant",
      content: `Yield forecast complete. Projected total: ${totalProjected.toFixed(2)} lbs across ${projects?.length || 0} active projects.`,
      code,
      language: "python",
      data: projects,
    }
  }

  const generateBatchLog = async (supabase: any): Promise<Message> => {
    const { data: projects } = await supabase
      .from("cultivation_projects")
      .select(`*, harvest_records(*), growth_observations(*)`)
      .order("created_at", { ascending: false })
      .limit(10)

    const code = `# Comprehensive Batch Log - Generated by Crowe Code
from datetime import datetime

print("CROWE LOGIC BATCH LOG REPORT")
print("=" * 60)
print(f"Generated: {datetime.now()}")
print(f"Total Batches: ${projects?.length || 0}")
print("=" * 60)

batches = ${JSON.stringify(
      projects?.map((p: any) => ({
        name: p.project_name,
        species: p.mushroom_species,
        status: p.status,
        harvests: p.harvest_records?.length || 0,
      })),
      null,
      2,
    )}

for batch in batches:
    print(f"\\nBatch: {batch['name']}")
    print(f"Species: {batch['species']}")
    print(f"Status: {batch['status']}")
    print(f"Harvests: {batch['harvests']}")
    print("-" * 60)`

    return {
      role: "assistant",
      content: `Generated batch logs for ${projects?.length || 0} cultivation projects with complete timeline data.`,
      code,
      language: "python",
      data: projects,
    }
  }

  return (
    <div className="flex flex-col h-full bg-black border border-[#485063] rounded-lg">
      {/* Header */}
      <div className="flex items-center justify-between px-4 py-3 bg-[#1a1f2e] border-b border-[#485063]">
        <div className="flex items-center gap-3">
          <AnimatedCroweAvatar mode="code" size={32} />
          <div>
            <h3 className="text-sm font-semibold text-white">Crowe Code</h3>
            <span className="text-xs text-[#a0a4a8]">Autonomous Agricultural Data Analyst</span>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <span className="text-xs text-[#4a90e2] font-mono">READY</span>
          <div className="w-2 h-2 rounded-full bg-[#4a90e2] animate-pulse" />
        </div>
      </div>

      {/* Messages */}
      <div className="flex-1 overflow-y-auto p-4 space-y-4 font-mono text-sm">
        {messages.length === 0 ? (
          <div className="h-full flex flex-col items-center justify-center text-center space-y-4">
            <AnimatedCroweAvatar mode="code" size={64} />
            <div className="space-y-2">
              <p className="text-white font-semibold">Crowe Code Ready</p>
              <p className="text-[#a0a4a8] text-xs max-w-md">
                Autonomous agricultural data analysis system. Analyze batches, track contamination, forecast yields,
                generate SOPs, and export comprehensive reports.
              </p>
            </div>
            <div className="grid grid-cols-2 gap-2 mt-4 w-full max-w-lg">
              {quickActions.map((action) => (
                <Button
                  key={action.label}
                  variant="outline"
                  size="sm"
                  onClick={() => handleQuickAction(action)}
                  className="bg-[#1a1f2e] border-[#485063] hover:bg-[#2d3648] hover:border-[#4a90e2] text-white justify-start"
                >
                  <action.icon className="w-4 h-4 mr-2 flex-shrink-0" />
                  <span className="text-xs">{action.label}</span>
                </Button>
              ))}
            </div>
          </div>
        ) : (
          messages.map((msg, idx) => (
            <div key={idx} className="space-y-2">
              <div className="flex items-center gap-2">
                <span className={msg.role === "user" ? "text-[#e5c07b]" : "text-[#4a90e2]"}>
                  {msg.role === "user" ? "user@crowe" : "crowe-code"}$
                </span>
              </div>
              <div className="text-white pl-4">{msg.content}</div>
              {msg.code && (
                <Card className="bg-[#0a0e14] border-[#485063] p-4 overflow-x-auto">
                  <div className="flex items-center justify-between mb-2">
                    <span className="text-xs text-[#a0a4a8] font-mono">{msg.language}</span>
                    <div className="flex gap-2">
                      <Button
                        size="sm"
                        variant="ghost"
                        onClick={() => navigator.clipboard.writeText(msg.code || "")}
                        className="text-[#4a90e2] hover:text-[#61afef]"
                      >
                        Copy
                      </Button>
                      {msg.data && (
                        <Button
                          size="sm"
                          variant="ghost"
                          onClick={() => {
                            const blob = new Blob([JSON.stringify(msg.data, null, 2)], { type: "application/json" })
                            const url = URL.createObjectURL(blob)
                            const a = document.createElement("a")
                            a.href = url
                            a.download = `crowe-code-data-${Date.now()}.json`
                            a.click()
                          }}
                          className="text-[#98c379] hover:text-[#a8d389]"
                        >
                          <Download className="w-3 h-3 mr-1" />
                          Export
                        </Button>
                      )}
                    </div>
                  </div>
                  <pre className="text-[#61afef] text-xs">
                    <code>{msg.code}</code>
                  </pre>
                </Card>
              )}
            </div>
          ))
        )}
        {isGenerating && (
          <div className="flex items-center gap-2 text-[#4a90e2]">
            <div className="flex gap-1">
              <span className="animate-bounce">.</span>
              <span className="animate-bounce animation-delay-200">.</span>
              <span className="animate-bounce animation-delay-400">.</span>
            </div>
            <span>Generating code</span>
          </div>
        )}
      </div>

      {/* Input */}
      <form onSubmit={handleSubmit} className="p-4 bg-[#1a1f2e] border-t border-[#485063]">
        <div className="flex gap-2">
          <Textarea
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder="Describe what you want to build..."
            className="flex-1 bg-black border-[#485063] text-white font-mono text-sm resize-none"
            rows={2}
            disabled={isGenerating}
          />
          <Button
            type="submit"
            disabled={!input.trim() || isGenerating}
            className="bg-[#4a90e2] hover:bg-[#61afef] text-white"
          >
            <Send className="w-4 h-4" />
          </Button>
        </div>
      </form>
    </div>
  )
}
